global:
  logLevel: debug
  splunk:
    hec:
      protocol: https
      insecureSSL: true
      host: $CI_SPLUNK_HOST
      token: $CI_SPLUNK_HEC_TOKEN

splunk-kubernetes-logging:
  kubernetes:
    insecureSSL: true
    clusterName: "ci-k8s-cluster"
  splunk:
    hec:
      indexName: ci_events
  image:
    name: splunk/fluentd-hec
    pullPolicy: Always
  k8sMetadata:
    podLabels:
      - app
  customMetadata:
    - name: customfield1
      value: customvalue1
    - name: customfield2
      value: customvalue2
  customMetadataAnnotations:
    - name: custom_field
      annotation: splunk.com/custom-field

splunk-kubernetes-metrics:
  kubernetes:
    useRestClientSSL: false
    insecureSSL: true
    kubeletPort: 10250
    clusterName: "ci-k8s-cluster-metrics"
  splunk:
    hec:
      indexName: ci_metrics
  image:
    name: splunk/k8s-metrics
    pullPolicy: Always
  imageAgg:
    name: splunk/k8s-metrics-aggr

splunk-kubernetes-objects:
  splunk:
    hec:
      indexName: ci_objects
  kubernetes:
    insecureSSL: true
    clusterName: "ci-k8s-cluster-objects"
  image:
    name: splunk/kube-objects
    pullPolicy: Always

