---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: splunk-kubernetes-metrics-aggregator
  labels:
    app: splunk-kubernetes-metrics
    version: 1.5.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-api-aggregator
subjects:
- kind: ServiceAccount
  name: splunk-kubernetes-metrics
  namespace: default
