---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-kubernetes-metrics
  labels:
    app: splunk-kubernetes-metrics
    version: 1.1.0
type: Opaque
data:
  splunk_hec_token: TVktU1BMVU5LLVRPS0VO
