---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk-kubernetes-logging
  labels:
    app: splunk-kubernetes-logging
    version: 1.4.12
roleRef:
  kind: ClusterRole
  name: splunk-kubernetes-logging
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: splunk-kubernetes-logging
  namespace: default
