---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-kubernetes-logging
  namespace: default
  labels:
    app: splunk-kubernetes-logging
    version: 1.5.0
type: Opaque
data:
  splunk_hec_token: TVktU1BMVU5LLVRPS0VO
