apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-kubernetes-metrics.fullname" . }}
  namespace: {{ template "splunk-kubernetes-metrics.namespace" . }}
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
    # system wide configurations
    <system>
      log_level {{ or .Values.logLevel .Values.global.logLevel | default "info" }}
    </system>
    <source>
      @type kubernetes_metrics
      tag kube.*
      node_name "#{ENV['NODE_NAME']}"
      {{- with .Values.kubernetes.kubeletAddress }}
      kubelet_address {{ . }}
      {{- end }}
      {{- with .Values.kubernetes.kubeletPort }}
      kubelet_port {{ . }}
      {{- end }}
      use_rest_client_ssl {{ .Values.kubernetes.useRestClientSSL }}
      {{- with .Values.kubernetes.insecureSSL }}
      insecure_ssl {{ . }}
      {{- end }}
      {{- if .Values.kubernetes.caFile }}
      ca_file /fluentd/etc/splunk/k8s_ca_file
      {{- end }}
      {{- with .Values.kubernetes.bearerTokenFile }}
      bearer_token_file {{ . }}
      {{- end }}
      {{- with .Values.kubernetes.secretDir }}
      secret_dir {{ . }}
      {{- end }}
      {{- with or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName }}
      cluster_name {{ . }}
      {{- end }}
      {{- with .Values.metricsInterval }}
      interval {{ . }}
      {{- end }}
    </source>

    <source>
      @id fluentd-monitor-agent
      @type monitor_agent
      bind {{ $.Values.global.monitoring_agent_bind_address | default "0.0.0.0"}}
      port 24220
      {{- if .Values.global.monitoring_agent_enabled }}
      tag monitor_agent
      {{- end }}
    </source>

    {{- if .Values.global.monitoring_agent_enabled }}
    # = filters for monitor agent =
    <filter monitor_agent>
      @type record_transformer
      enable_ruby
      <record>
        source namespace:${ENV['MY_NAMESPACE']}/pod:${ENV['MY_POD_NAME']}
        sourcetype "fluentd:monitor-agent"
        {{- with or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName | default "cluster_name" }}
        cluster_name {{ . }}
        {{- end }}
        {{- with or .Values.global.monitoring_agent_index_name .Values.global.splunk.hec.indexName | default "main" }}
        splunk_index {{ . }}
        {{- end }}
        {{- if .Values.customMetadata }}
        {{- range .Values.customMetadata }}
        {{ .name }} "{{ .value }}"
        {{- end }}
        {{- end }}
      </record>
    </filter>
    {{- end }}

    <filter kube.**>
      @type record_modifier
      <record>
        metric_name ${tag}
        {{- with or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName }}
        cluster_name {{ . }}
        {{- end }}
      </record>
    </filter>
    <filter kube.node.**>
      @type record_modifier
      <record>
        source ${record['node']}
      </record>
    </filter>
    <filter kube.pod.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}
      </record>
    </filter>
    <filter kube.sys-container.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}/${record['name']}
      </record>
    </filter>
    <filter kube.container.**>
      @type record_modifier
      <record>
        source ${record['node']}/${record['pod-name']}/${record['container-name']}
      </record>
    </filter>
    # = custom filters specified by users =
    {{- range $name, $filterDef := .Values.customFilters }}
    {{- if and $filterDef.tag $filterDef.type }}
    <filter {{ $filterDef.tag }}>
      @type {{ $filterDef.type }}
      {{- if $filterDef.body }}
      {{ $filterDef.body | indent 8 }}
      {{- end }}
    </filter>
    {{- end }}
    {{- end }}
    <match kube.**>
      @type splunk_hec
      data_type metric
      metric_name_key metric_name
      metric_value_key value
      protocol {{ or .Values.splunk.hec.protocol .Values.global.splunk.hec.protocol }}
      {{- with or .Values.splunk.hec.host .Values.global.splunk.hec.host }}
      hec_host {{ . | quote }}
      {{- end }}
      {{- with or .Values.splunk.hec.port .Values.global.splunk.hec.port }}
      hec_port {{ . }}
      {{- end }}
      {{- with or .Values.splunk.hec.endpoint .Values.global.splunk.hec.endpoint }}
      hec_endpoint {{ . | quote }}
      {{- end }}
      {{- with or .Values.splunk.hec.fullUrl .Values.global.splunk.hec.fullUrl }}
      full_url {{ . | quote }}
      {{- end }}
      consume_chunk_on_4xx_errors {{ template "splunk-kubernetes-metrics.should_consume_chunk_on_4xx_errors" . }}
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['NODE_NAME']}"
      {{- with or .Values.splunk.hec.indexName .Values.global.splunk.hec.indexName }}
      index {{ . }}
      {{- end }}
      source ${tag}
      sourcetype kube:metrics
      insecure_ssl {{ or .Values.splunk.hec.insecureSSL .Values.global.splunk.hec.insecureSSL | default false }}
      {{- if or .Values.splunk.hec.clientCert .Values.global.splunk.hec.clientCert }}
      client_cert /fluentd/etc/splunk/hec_client_cert
      {{- end }}
      {{- if  or .Values.splunk.hec.clientKey .Values.global.splunk.hec.clientKey }}
      client_key /fluentd/etc/splunk/hec_client_key
      {{- end }}
      {{- if or .Values.splunk.hec.caFile .Values.global.splunk.hec.caFile }}
      ca_file /fluentd/etc/splunk/hec_ca_file
      {{- end }}
      app_name {{ .Chart.Name }}
      app_version {{ .Chart.Version }}
      {{- with .Values.buffer }}
      <buffer>
      {{- range $parameter, $value := . }}
        {{ $parameter }} {{ $value }}
      {{- end }}
      </buffer>
      {{- end }}
    </match>
    {{- if .Values.global.monitoring_agent_enabled }}
    <match monitor_agent>
      @type splunk_hec
      protocol {{ or .Values.splunk.hec.protocol .Values.global.splunk.hec.protocol }}
      {{- with or .Values.splunk.hec.host .Values.global.splunk.hec.host }}
      hec_host {{ . | quote }}
      {{- end }}
      {{- with or .Values.splunk.hec.port .Values.global.splunk.hec.port }}
      hec_port {{ . }}
      {{- end }}
      {{- with or .Values.splunk.hec.endpoint .Values.global.splunk.hec.endpoint }}
      hec_endpoint {{ . | quote }}
      {{- end }}
      {{- with or .Values.splunk.hec.fullUrl .Values.global.splunk.hec.fullUrl }}
      full_url {{ . | quote }}
      {{- end }}
      consume_chunk_on_4xx_errors {{ template "splunk-kubernetes-metrics.should_consume_chunk_on_4xx_errors" . }}
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['NODE_NAME']}"
      index_key splunk_index
      source_key source
      sourcetype_key sourcetype
      <fields>
        {{- if or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName }}
        cluster_name
        {{- end }}
        {{- if .Values.customMetadata }}
        {{- range .Values.customMetadata }}
        {{ .name }}
        {{- end }}
        {{- end }}
      </fields>
      insecure_ssl {{ or .Values.splunk.hec.insecureSSL .Values.global.splunk.hec.insecureSSL | default false }}
      {{- if or .Values.splunk.hec.clientCert .Values.global.splunk.hec.clientCert }}
      client_cert /fluentd/etc/splunk/hec_client_cert
      {{- end }}
      {{- if  or .Values.splunk.hec.clientKey .Values.global.splunk.hec.clientKey }}
      client_key /fluentd/etc/splunk/hec_client_key
      {{- end }}
      {{- if or .Values.splunk.hec.caFile .Values.global.splunk.hec.caFile }}
      ca_file /fluentd/etc/splunk/hec_ca_file
      {{- end }}
      app_name {{ .Chart.Name }}
      app_version {{ .Chart.Version }}
      {{- with .Values.buffer }}
      <buffer>
      {{- range $parameter, $value := . }}
        {{ $parameter }} {{ $value }}
      {{- end }}
      </buffer>
      {{- end }}
      <format>
        @type json
      </format>
    </match>
    {{- end }}
