apiVersion: v1
version: 1.4.7
appVersion: 1.4.7
name: splunk-kubernetes-metrics
description: Collect metrics with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/main/helm-chart/charts/splunk-kubernetes-metrics
sources:
- https://github.com/splunk/splunk-connect-for-kubernetes/tree/main/helm-chart/charts/splunk-kubernetes-metrics
- https://github.com/splunk/fluent-plugin-splunk-hec
- https://github.com/splunk/fluent-plugin-kubernetes-metrics
- https://github.com/splunk/fluent-plugin-k8s-metrics-agg
keywords:
- splunk
- monitoring
- metric
maintainers:
- name: Splunk Inc.
  email: DataEdge@splunk.com
