apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-kubernetes-objects.fullname" . }}
  namespace: {{ template "splunk-kubernetes-objects.namespace" . }}
  labels:
    app: {{ template "splunk-kubernetes-objects.name" . }}
    chart: {{ template "splunk-kubernetes-objects.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
    <system>
      log_level {{ or .Values.logLevel .Values.global.logLevel }}
    </system>

    {{- range $apiGroup, $apiVersions := .Values.objects }}
    {{- range $apiVersion, $objects := $apiVersions }}
    <source>
      @type kubernetes_objects
      tag kube.objects.*
      {{- with $.Values.kubernetes.url }}
      kubernetes_url {{ . }}
      {{- end }}
      api_version {{ $apiVersion | quote }}
      {{- if eq ($apiGroup | lower) "core" }}
      api_endpoint "api"
      {{- else }}
      api_endpoint {{ list "apis" $apiGroup | join "/" | quote }}
      {{- end }}
      insecure_ssl {{ $.Values.kubernetes.insecureSSL }}
      {{- with $.Values.kubernetes.secretDir }}
      secret_dir {{ . }}
      {{- end }}
      {{- if $.Values.kubernetes.clientCert }}
      client_cert /fluentd/etc/splunk/k8s_client_cert
      {{- end }}
      {{- if $.Values.kubernetes.clientKey }}
      client_key /fluentd/etc/splunk/k8s_client_key
      {{- end }}
      {{- if $.Values.kubernetes.caFile }}
      ca_file /fluentd/etc/splunk/k8s_ca_file
      {{- end }}
      {{- with $.Values.kubernetes.bearerTokenFile }}
      bearer_token_file {{ . }}
      {{- end }}
      {{- if $.Values.checkpointFile.volume }}
      <storage>
        path /fluentd/var/checkpoints/{{ $.Values.checkpointFile.name | default "kubernetes-objects" }}
      </storage>
      {{- end }}
      {{- range $objects }}
      {{- if eq (.mode | default "pull" | lower) "pull" }}
      <pull>
      {{- else }}
      <watch>
      {{- end }}
        resource_name {{ required "object name is required" .name }}
        {{- with .namespace }}
        namespace {{ . }}
        {{- end }}
        {{- with .labelSelector }}
        label_selector {{ . }}
        {{- end }}
        {{- with .fieldSelector }}
        field_selector {{ . }}
        {{- end }}
        {{- with .interval }}
        interval {{ . }}
        {{- end }}
      {{- if eq (.mode | default "pull" | lower) "pull" }}
      </pull>
      {{- else }}
      </watch>
      {{- end }}
      {{- end }}
    </source>
    {{- end }}
    {{- end }}

    <source>
      @id fluentd-monitor-agent
      @type monitor_agent
      bind {{ $.Values.global.monitoring_agent_bind_address | default "0.0.0.0"}}
      port 24220
      {{- if .Values.global.monitoring_agent_enabled }}
      tag monitor_agent
      {{- end }}
    </source>

    {{- if .Values.global.monitoring_agent_enabled }}
    # = filters for monitor agent =
    <filter monitor_agent>
      @type jq_transformer
      jq ".record.source = \"namespace:#{ENV['MY_NAMESPACE']}/pod:#{ENV['MY_POD_NAME']}\" | .record.sourcetype = \"fluentd:monitor-agent\" | .record.cluster_name = \"{{ or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName | default "cluster_name" }}\" | .record.splunk_index = \"{{ or .Values.global.monitoring_agent_index_name .Values.global.splunk.hec.indexName .Values.splunk.hec.indexName | default "main" }}\" {{- if .Values.customMetadata }}{{- range .Values.customMetadata }}| .record.{{ .name }} = \"{{ .value }}\" {{- end }}{{- end }} | .record"
    </filter>
    {{- end }}

    <filter kube.**>
      @type jq_transformer
      # in ruby '\\' will escape and become just '\', since we need two '\' in the `gsub` jq filter, it becomes '\\\\'.
      jq '.record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\\\."; ":")) | .record'
    </filter>

    <filter kube.**>
      @type jq_transformer
      jq '.record.cluster_name = "{{ or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName }}" | .record'
    </filter>

    # = custom filters specified by users =
    {{- range $name, $filterDef := .Values.customFilters }}
    {{- if and $filterDef.tag $filterDef.type }}
    <filter {{ $filterDef.tag }}>
      @type {{ $filterDef.type }}
      {{- if $filterDef.body }}
      {{ $filterDef.body | indent 8 }}
      {{- end }}
    </filter>
    {{- end }}
    {{- end }}

    <match **>
      @type splunk_hec
      protocol {{ or .Values.splunk.hec.protocol .Values.global.splunk.hec.protocol | default "https" }}
      {{- with or .Values.splunk.hec.host .Values.global.splunk.hec.host }}
      hec_host {{ . | quote }}
      {{- end }}
      {{- with or .Values.splunk.hec.port .Values.global.splunk.hec.port }}
      hec_port {{ . }}
      {{- end }}
      {{- with or .Values.splunk.hec.endpoint .Values.global.splunk.hec.endpoint }}
      hec_endpoint {{ . | quote }}
      {{- end }}
      {{- with or .Values.splunk.hec.fullUrl .Values.global.splunk.hec.fullUrl }}
      full_url {{ . | quote }}
      {{- end }}
      consume_chunk_on_4xx_errors {{ template "splunk-kubernetes-objects.should_consume_chunk_on_4xx_errors" . }}
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['NODE_NAME']}"
      source_key source
      sourcetype_key sourcetype
      {{- if or .Values.splunk.hec.indexRouting .Values.global.splunk.hec.indexRouting }}
      index_key index
      {{- else }}
      {{- with or .Values.splunk.hec.indexName .Values.global.splunk.hec.indexName }}
      index {{ . }}
      {{- end }}
      {{- end }}
      insecure_ssl {{ or .Values.splunk.hec.insecureSSL .Values.global.splunk.hec.insecureSSL }}
      {{- if or .Values.splunk.hec.clientCert .Values.global.splunk.hec.clientCert }}
      client_cert /fluentd/etc/splunk/hec_client_cert
      {{- end }}
      {{- if or .Values.splunk.hec.clientKey .Values.global.splunk.hec.clientKey }}
      client_key /fluentd/etc/splunk/hec_client_key
      {{- end }}
      {{- if or .Values.splunk.hec.caFile .Values.global.splunk.hec.caFile }}
      ca_file /fluentd/etc/splunk/hec_ca_file
      {{- end }}
      <fields>
        {{- if or .Values.kubernetes.clusterName .Values.global.kubernetes.clusterName }}
        cluster_name
        {{- end }}
        {{- range .Values.indexFields }}
        {{ . }}
        {{- end }}
      </fields>
      app_name {{ .Chart.Name }}
      app_version {{ .Chart.Version }}
      {{- with .Values.buffer }}
      <buffer>
      {{- range $parameter, $value := . }}
        {{ $parameter }} {{ $value }}
      {{- end }}
      </buffer>
      {{- end }}
      {{- if .Values.global.monitoring_agent_enabled }}
      <format monitor_agent>
        @type json
      </format>
      {{- end }}
    </match>
