---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    version: 1.4.12
roleRef:
  kind: ClusterRole
  name: splunk-kubernetes-objects
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: splunk-kubernetes-objects
  namespace: default
