---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    version: 1.4.12
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - "*"
  hostNetwork: false
  hostIPC: false
  hostPID: false
  volumes:
  - "*"
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
